on:
  workflow_dispatch:
    inputs:
      version:
        description: Web Version
        default: v1.0.0
        required: true

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: 🔨 Build Project
      run: |
        npm install
        npm run generate
            
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: roman-goetzmann.de
        username: 217993-194-khri8
        password: ${{ secrets.password }}
        local-dir: './dist/'
        server-dir: 'wahl2023/'